"""Stub a specification file for every figure referenced by the manuscript.

A figure with no written purpose cannot be reviewed against one, so the
redraw starts here. This does not invent the purpose: it collects what the
manuscript already knows (the caption, the width the figure is placed at,
the surrounding section, the drawing function that produces it) into
figures/spec/<name>.md, leaving the judgement calls blank for a person.

Existing specs are never overwritten.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
SPEC_DIR = PROJECT_ROOT / "figures" / "spec"
TEXT_WIDTH_IN = 4.5  # 6x9 trim, 0.875in spine, 0.625in fore-edge

FIGURE_RE = re.compile(
    r"\\begin\{figure\}(?:\[[^\]]*\])?(.*?)\\end\{figure\}", re.S
)
GRAPHIC_RE = re.compile(r"\\includegraphics(?:\[([^\]]*)\])?\{([^}]*)\}")
CAPTION_RE = re.compile(r"\\caption\{(.*)", re.S)
WIDTH_RE = re.compile(r"width\s*=\s*([\d.]+)\s*\\(?:text|line)width")


def balanced(text: str) -> str:
    """Return the contents of a brace group that has already been opened."""
    depth, out = 1, []
    for char in text:
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                break
        out.append(char)
    return "".join(out)


def clean(text: str) -> str:
    for _ in range(4):
        text = re.sub(r"\\(?:emph|textit|textbf|textsc|texttt)\{([^{}]*)\}", r"\1", text)
    text = re.sub(r"\\(?:label|index)\{[^}]*\}", "", text)
    text = re.sub(r"\\[a-zA-Z]+\*?", " ", text)
    text = re.sub(r"[{}~]", " ", text)
    text = text.replace("---", "\u2014").replace("--", "\u2013")
    return re.sub(r"\s+", " ", text).strip()


def drawing_functions() -> dict[str, tuple[str, str]]:
    """Map figure name to the (script, function) that draws it."""
    out = {}
    for script in sorted((PROJECT_ROOT / "scripts" / "figures").glob("ch*.py")):
        chapter = int(script.stem[2:])
        text = script.read_text(encoding="utf-8")
        current = ""
        for line in text.splitlines():
            match = re.match(r"def (\w+)\(", line)
            if match:
                current = match.group(1)
            save = re.search(r"save_figure\([^,]+,\s*['\"]([^'\"]+)['\"]", line)
            if save:
                out[f"ch{chapter:02d}-{save.group(1)}"] = (script.name, current)
    return out


def scan() -> list[dict]:
    found = []
    drawings = drawing_functions()
    for tex in sorted((PROJECT_ROOT / "src").rglob("*.tex")):
        text = tex.read_text(encoding="utf-8", errors="ignore")
        sections = [(m.start(), clean(balanced(text[m.end():])))
                    for m in re.finditer(r"\\section\{", text)]
        for match in FIGURE_RE.finditer(text):
            body = match.group(1)
            graphic = GRAPHIC_RE.search(body)
            if not graphic:
                continue
            options, path = graphic.group(1) or "", graphic.group(2)
            name = Path(path).stem
            width_match = WIDTH_RE.search(options)
            fraction = float(width_match.group(1)) if width_match else 1.0
            caption_match = CAPTION_RE.search(body)
            caption = clean(balanced(caption_match.group(1))) if caption_match else ""
            label = re.search(r"\\label\{([^}]*)\}", body)
            section = ""
            for position, title in sections:
                if position < match.start():
                    section = title
            found.append({
                "name": name,
                "file": str(tex.relative_to(PROJECT_ROOT)),
                "kind": "photo" if "photos/" in path else "generated",
                "fraction": fraction,
                "printed_in": round(fraction * TEXT_WIDTH_IN, 2),
                "caption": caption,
                "label": label.group(1) if label else "",
                "section": section,
                "drawn_by": drawings.get(name, ("", "")),
            })
    return found


TEMPLATE = """# {name}

<!-- Stub generated by scripts/figures/make_specs.py from the manuscript.
     Fill in the blank fields. This file is the brief the redraw works to
     and the checklist the figure is reviewed against. -->

| | |
|---|---|
| Appears in | `{file}`{section_note} |
| Reference | `{label}` |
| Printed width | {printed_in} in ({fraction:g} of the 4.5 in measure) |
| Drawn by | {drawn} |
| Kind | {kind} |

## Question it answers

<!-- One sentence. If you cannot write one, the figure should be cut. -->

## What it shows

<!-- The data, geometry or process. Name the quantities and their units. -->

## Where the content comes from

<!-- Measured data with a citation; a geometric construction; a schematic
     drawn from a described instrument. A figure asserting numbers needs a
     source in the bibliography exactly as a sentence would. -->

## Form

<!-- plot | schematic | timeline | flowchart | map | photograph
     and why that form rather than another. -->

## Sentence it supports

<!-- Quote the line of the text the reader is looking at when they turn to
     this figure. -->

## Current caption

> {caption}

## Review

- [ ] Question above is answerable and worth a figure
- [ ] Every label legible at {printed_in} in wide (7 pt floor)
- [ ] Reads correctly in greyscale
- [ ] No information in colour alone
- [ ] Caption says what to look at, not just what it is
- [ ] Source recorded above, and in the bibliography if it asserts data

## Status

`stub`  <!-- stub | specified | redrawn | approved -->
"""


def main() -> int:
    figures = scan()
    SPEC_DIR.mkdir(parents=True, exist_ok=True)
    written = skipped = 0
    for figure in figures:
        path = SPEC_DIR / f"{figure['name']}.md"
        if path.exists():
            skipped += 1
            continue
        script, function = figure["drawn_by"]
        drawn = f"`{script}` &rarr; `{function}()`" if script else "not generated from code"
        section_note = f" &mdash; {figure['section']}" if figure["section"] else ""
        path.write_text(
            TEMPLATE.format(section_note=section_note, drawn=drawn, **figure),
            encoding="utf-8",
        )
        written += 1

    narrow = [f for f in figures if f["printed_in"] < 2.8]
    print(f"{len(figures)} figures referenced by the manuscript")
    print(f"{written} specs written, {skipped} already existed")
    if narrow:
        print(f"\n{len(narrow)} printed under 2.8 in wide, where labels are most at risk:")
        for figure in sorted(narrow, key=lambda f: f["printed_in"])[:12]:
            print(f"  {figure['printed_in']:.2f} in  {figure['name']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
