"""Report how far each part of the book has moved through the gates.

Reads the ledgers under review/ and figures/ and writes docs/status.md, which
is the single place to look for what is left to do. Run with `make status`.
"""

from __future__ import annotations

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLAIMS_DIR = PROJECT_ROOT / "review" / "claims"
REFS_FILE = PROJECT_ROOT / "review" / "refs" / "verification.yaml"
MANIFEST = PROJECT_ROOT / "figures" / "manifest.yaml"
SPEC_DIR = PROJECT_ROOT / "figures" / "spec"
OUT = PROJECT_ROOT / "docs" / "status.md"

DONE, OPEN = "●", "○"


def claim_counts() -> dict[str, dict[str, int]]:
    out = {}
    for path in sorted(CLAIMS_DIR.glob("*.yaml")):
        counts: dict[str, int] = {}
        for line in path.read_text(encoding="utf-8").splitlines():
            match = re.match(r"\s+status:\s*(\S+)", line)
            if match:
                counts[match.group(1)] = counts.get(match.group(1), 0) + 1
        out[path.stem] = counts
    return out


def ref_counts() -> dict[str, int]:
    if not REFS_FILE.exists():
        return {}
    counts: dict[str, int] = {}
    for line in REFS_FILE.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s+status:\s*(\S+)", line)
        if match:
            counts[match.group(1)] = counts.get(match.group(1), 0) + 1
    return counts


def manifest_counts() -> dict[str, int]:
    if not MANIFEST.exists():
        return {}
    counts: dict[str, int] = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s+status:\s*(\S+)", line)
        if match:
            counts[match.group(1)] = counts.get(match.group(1), 0) + 1
    return counts


def bar(done: int, total: int, width: int = 22) -> str:
    if not total:
        return "-" * width
    filled = round(width * done / total)
    return DONE * filled + OPEN * (width - filled)


def figure_refs() -> set[str]:
    found = set()
    for tex in (PROJECT_ROOT / "src").rglob("*.tex"):
        found |= set(re.findall(r"generated/([A-Za-z0-9_-]+)", tex.read_text(encoding="utf-8", errors="ignore")))
    return found


def main() -> int:
    claims = claim_counts()
    refs = ref_counts()
    images = manifest_counts()
    figures = figure_refs()
    specs = {p.stem for p in SPEC_DIR.glob("*.md")} if SPEC_DIR.exists() else set()

    lines = [
        "# Status",
        "",
        "Generated by `make status`. Do not edit by hand.",
        "",
        "## Verification",
        "",
    ]

    total_claims = sum(sum(c.values()) for c in claims.values())
    settled = sum(
        c.get("verified", 0) + c.get("corrected", 0) + c.get("removed", 0)
        for c in claims.values()
    )
    ref_total = sum(refs.values())
    ref_ok = refs.get("resolved", 0)
    img_total = sum(images.values())
    img_ok = images.get("present", 0)

    lines += [
        "| Track | Progress | Done | Total |",
        "|---|---|---:|---:|",
        f"| Claims | `{bar(settled, total_claims)}` | {settled} | {total_claims} |",
        f"| References | `{bar(ref_ok, ref_total)}` | {ref_ok} | {ref_total} |",
        f"| Figure specs | `{bar(len(specs & figures), len(figures))}` | {len(specs & figures)} | {len(figures)} |",
        f"| Images in manifest | `{bar(img_ok, img_total)}` | {img_ok} | {img_total} |",
        "",
    ]

    if refs:
        lines += ["### References by status", ""]
        for status in ("resolved", "ambiguous", "not-found"):
            if status in refs:
                lines.append(f"- **{status}**: {refs[status]}")
        lines.append("")

    lines += [
        "## Claims by file",
        "",
        "| File | Unverified | Verified | Corrected | Removed | Total |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for name in sorted(claims):
        c = claims[name]
        total = sum(c.values())
        lines.append(
            f"| {name} | {c.get('unverified', 0)} | {c.get('verified', 0)} | "
            f"{c.get('corrected', 0)} | {c.get('removed', 0)} | {total} |"
        )
    lines.append("")

    missing = sorted(figures - specs)
    if missing:
        lines += [
            "## Figures without a specification",
            "",
            f"{len(missing)} of {len(figures)}. A figure with no written purpose "
            "cannot be reviewed against one.",
            "",
        ]
        lines.append(", ".join(f"`{name}`" for name in missing[:40]))
        if len(missing) > 40:
            lines.append(f"\n...and {len(missing) - 40} more.")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"claims     {settled}/{total_claims} settled")
    print(f"references {ref_ok}/{ref_total} resolved")
    print(f"figures    {len(specs & figures)}/{len(figures)} specified")
    print(f"images     {img_total} in manifest")
    print(f"written to {OUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
